name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Prepare deployment
        run: |
          echo "Deploying fresh copy of all files..."
          echo "Deployment timestamp: $(date)" > deployment_info.txt
          echo "Commit SHA: ${{ github.sha }}" >> deployment_info.txt
          echo "Cache-Bust: $(date +%s)" >> deployment_info.txt
          # Add cache-busting meta tags to all HTML files
          find . -name "*.html" -type f -exec sed -i '' 's/<meta http-equiv="Cache-Control"[^>]*>//g' {} \;
          find . -name "*.html" -type f -exec sed -i '' 's/<meta http-equiv="Pragma"[^>]*>//g' {} \;
          find . -name "*.html" -type f -exec sed -i '' 's/<meta http-equiv="Expires"[^>]*>//g' {} \;
          find . -name "*.html" -type f -exec sed -i '' '/<meta name="viewport"/a\
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">\
    <meta http-equiv="Pragma" content="no-cache">\
    <meta http-equiv="Expires" content="0">\
    <meta name="cache-bust" content="'"$(date +%s)"'">' {} \;
          ls -la
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          retention-days: 1
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          timeout: 600000